#Tutorial Python

Traducido y adaptado por [Pablo Andrés Uriza](https://pa-uriza.github.io/) de la adaptación hecha por [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) y [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335) para el curso `CS228`, del tutorial de Python para el curso `CS231n` hecho por Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).

##Introducción

Python es un gran lenguaje de programación de propósito general por sí solo, pero con la ayuda de algunas bibliotecas populares (numpy, scipy, matplotlib) se convierte en un poderoso entorno para la computación científica.

Esta sección servirá como un curso acelerado sobre el lenguaje de programación Python y sobre el uso de Python para la computación científica.

En este tutorial, cubriremos:

* Python básico: tipos de datos básicos (contenedores, listas, diccionarios, conjuntos, tuplas), funciones, clases
* Numpy: matrices, indexación de matrices, tipos de datos, matemáticas de matrices, *broadcasting*
* Matplotlib: plots, subplots

##Python básico

Python es un lenguaje de programación multiparadigma de escritura dinámica de alto nivel. A menudo se dice que el código Python es casi como un pseudocódigo, ya que le permite expresar ideas muy poderosas en muy pocas líneas de código mientras es muy legible. Como ejemplo, aquí hay una implementación del algoritmo clásico de ordenación rápida en Python:

In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


###Versiones de Python

Por mucho tiempo hubo dos versiones compatibles diferentes de Python, 2.7 y 3.X. Un tanto confuso, Python 3.0 introdujo muchos cambios incompatibles con versiones anteriores en el lenguaje, por lo que el código escrito para 2.7 puede no funcionar en 3.X y viceversa. Para esta clase, todo el código usará Python 3.7.

Puede verificar su versión de Python en la línea de comando ejecutando `python --version` .:

###Tipos de datos básicos

####Números

Los enteros y reales funcionan como esperaríamos de otros lenguajes:

In [ ]:
x = 3
print(x, type(x))

3 <class 'int'>


In [ ]:
print(x + 1)   # Suma;
print(x - 1)   # Resta;
print(x * 2)   # Multiplicación;
print(x ** 2)  # Potenciación;

4
2
6
9


In [ ]:
x += 1
print(x)  # Imprime "4"
x *= 2
print(x)  # Imprime "8"

4
8


In [ ]:
y = 2.5
print(type(y)) # Imprime "<type 'float'>"
print(y, y + 1, y * 2, y ** 2) # Imprime "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


Tenga en cuenta que, a diferencia de muchos lenguajes, Python no tiene operadores unarios de incremento (x ++) o decremento (x--).

Python también tiene tipos integrados para enteros largos (*long integers*) y números complejos; puede encontrar todos los detalles en la [documentación](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-long-complex).

####Booleanos

Python implementa todos los operadores habituales para la lógica booleana, pero usa palabras en inglés en lugar de símbolos (&&, ||, etc.)

In [ ]:
t, f = True, False
print(type(t)) # Imprime "<type 'bool'>"

Ahora veamos las operaciones:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

####Strings

In [ ]:
hello = 'hello'   # Los strings pueden declararse usando comillas sencillas
world = "world"   # o comillas dobles, no importa.
print (hello, len(hello))

hello 5


In [ ]:
hw = hello + ' ' + world  # Concatenación de Strings
print (hw)  # Imprime "hello world"

In [ ]:
hw = f'{hello} {world} {2021}'  # Formateo de strings
print (hw12)  # Imprime "hello world 2021"

String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print (s.capitalize())  # Pone la primera letra en mayúscula a un string; Imprime "Hello"
print (s.upper())       # Convierte la string a mayúscula sostenida; Imprime "HELLO"
print (s.rjust(7))      # Justifica a la derecha una string añadiendo espacios a la izquierda; Imprime "  hello"
print (s.center(7))     # Centra una string añadiendo espacios a ambos lados; Imprime " hello "
print (s.replace('l', '(ell)'))  # Reemplaza todas las instancias de una substring con otra;
                               # imprime "he(ell)(ell)o"
print ('  world '.strip())  # Remueve los espacios en blanco al inicio y al final; Imprime "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


Puede encontrar una lista de todos los métodos de cadena en la [documentación](https://docs.python.org/3/library/stdtypes.html#string-methods).

###Contenedores

Python incluye varios tipos de contenedores integrados: listas, diccionarios, conjuntos y tuplas.

####Lists

Una lista es el equivalente en Python de un arreglo, pero se puede cambiar de tamaño y puede contener elementos de diferentes tipos:

In [ ]:
xs = [3, 1, 2]   # Crea una lista
print(xs, xs[2])
print(xs[-1])    # Lo indices negativos cuentan desde el final de la lista; Imprime "2

[3, 1, 2] 2
2


In [ ]:
xs[2] = 'foo'    # Las listas pueden contener elementos de diferentes tipos
print(xs)

[3, 1, 'foo']


In [ ]:
xs.append('bar') # Agrega un nuevo elemento al final de la lista
print(xs)  

[3, 1, 'foo', 'bar']


In [ ]:
x = xs.pop()     # Remueve y retorna el último elemento de la lista
print(x, xs) 

Como de costumbe, todos los detalles de las listas se encuentran en la [documentación](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists).

####Slicing

Además de acceder a los elementos de la lista de uno en uno, Python proporciona una sintaxis concisa para acceder a las sublistas; esto se conoce como *slicing* (rebanar):

In [ ]:
nums = list(range(5))    # creamos una lita de enteros a partir de la función range
print(nums)              # Imprime "[0, 1, 2, 3, 4]"
print(nums[2:4])         # Obtiene una slice desde el índice 2 al 4 (exclusive); imprime "[2, 3]"
print(nums[2:])          # Obtiene una slice desde el índice 2 al final; imprime "[2, 3, 4]"
print(nums[:2])          # Obtiene una slice desde el inicio al índice 2 (exclusive); imprime "[0, 1]"
print(nums[:])           # Obtiene una slice de toda la lista; imprime ["0, 1, 2, 3, 4]"
print(nums[:-1])         # Los índices de una slice pueden ser negativos; imprime ["0, 1, 2, 3]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]


####Bucles

Es posible hacer bucles sobre elementos de una lista así:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


Si desea acceder al índice de cada elemento dentro del cuerpo de un bucle, use la función incorporada `enumerate`:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print (f'#{idx + 1}: {animal}')

####List comprehensions:

A la hora de programar, con frecuencia queremos transformar un tipo de datos en otro. Como ejemplo simple, considere el siguiente código que calcula números cuadrados:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


Podemos simplificar este código usando una *list comprehension*:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

Las *list comprehensions* también pueden contener algunas condiciones:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

####Diccionarios

Un diccionario almacena pares (key, value). Puedes usarlo así:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Crea un nuevo diccionario con alguna data
print(d['cat'])       # Obtiene la una entrada del diccionario; imprime "cute"
print('cat' in d)     # Revisa si un diccionario tiene una *key* dada; imprime "True"

cute
True


In [ ]:
d['fish'] = 'wet'    # define una entrada para el diccionario
print (d['fish'])    # Imprime "wet"
print(d)

wet
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}


In [ ]:
print (d['monkey'])  # KeyError: 'monkey' not a key of d -> La llave 'momnkey' no existe en el diccionario d

In [ ]:
print (d.get('monkey', 'N/A'))  # Obtiene un elemento considerando un valor por defecto; imprime "N/A"
print (d.get('fish', 'N/A'))    # Obtiene un elemento considerando un valor por defecto; imprime "wet"

In [ ]:
del d['fish']        # Remueve un elemento de un diccionario
print (d.get('fish', 'N/A')) # "fish" ya no es una llave; imprime "N/A"

Todo lo que se necesita saber sobre los diccionarios está en la [documentación](https://docs.python.org/3/library/stdtypes.html#dict).

Es fácil iterar sobre las *keys* de un diccionario:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print(f'A {animal} has {legs} legs')

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Si quieres acceder a las *keys* y su respectivos *values*, usa el método iteritems:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print (f'A {animal} has {legs} legs')

Dictionary comprehensions: Estos son similares a las *list comprehensions*, pero permiten construir diccionarios fácilmente. Por ejemplo:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

####Conjuntos

Un conjunto es una colección sin orden de elementos distintos. Como ejemplo simple, considera lo siguiente:

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Revisa si un elemento está en un conjunto; imprime "True"
print('fish' in animals)  # imprime "False"


True
False


In [ ]:
animals.add('fish')      # Agrega un elemento al conjunto
print('fish' in animals)
print(len(animals))     # Número de elementos en un conjunto;

In [ ]:
animals.add('cat')       # Agregar un elemento que ya está en el conjunto no hace nada
print(animals)
print(len(animals))       
animals.remove('cat')    # Remueve un elemento de un conjunto
print(animals)
print(len(animals))       

_Bucles_: La iteración sobre un conjunto tiene la misma sintaxis que la iteración sobre una lista; sin embargo, dado que los conjuntos no están ordenados, no puede hacer suposiciones sobre el orden en el que visita los elementos del conjunto:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('{}: {}'.format(idx + 1, animal))
# Imprime "#1: fish", "#2: dog", "#3: cat"

Set comprehensions: Como con las listas y los diccionarios, podemos construir conjuntos fácilmente usando *set comprehension*s:

In [ ]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

####Tuplas

Una tupla es una lista ordenada (inmutable) de valores. Una tupla es en muchos aspectos similar a una lista; una de las diferencias más importantes es que las tuplas se pueden utilizar como claves en diccionarios y como elementos de conjuntos, mientras que las listas no. Aquí hay un ejemplo trivial:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Crea un diccionario con tuplas como keys
t = (5, 6)       # Crea una tuple
print(type(t))
print(d[t])       
print(d[(1, 2)])

<class 'tuple'>
5
1


In [ ]:
t[0] = 1  #La tupla es inmutable. No permite asignación.

TypeError: ignored

###Funciones

Las funciones de Python se definen usando la palabra clave `def`. Por ejemplo:

In [ ]:
def sign(x):
  if x > 0:
      return 'positive'
  elif x < 0:
      return 'negative'
  else:
      return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


A menudo definiremos funciones para tomar argumentos de palabras clave opcionales, como loud en este ejemplo:

In [ ]:
def hello(name, loud=False):
    if loud:
        print(f'HELLO, {name.upper()}')
    else:
        print(f'Hello, {name}!')

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


###Clases

La sintaxis para definir clases en Python es sencilla:

In [ ]:
class Greeter:    # Saludador

    # Constructor
    def __init__(self, name):
        self.name = name  # Crea un atributo (variable) de la instancia

    # Método de la instancia
    def greet(self, loud=False):
        if loud:
            print(f'HELLO, {self.name.upper()}!') #Para acceder a un atributo dentro de la misma clase, se usa la palabra self y luego el nombre del atributo
        else:
            print(f'Hello, {self.name}'.format())

g = Greeter('Fred')  # Cosntruye una instancia de la clase Greeter
g.greet()            # Llama el método de la instancia g; imprime "Hello, Fred"
g.greet(loud=True)   # Llama el método de la instancia g; imprime "HELLO, FRED!"

##Numpy

Numpy es la biblioteca central para la computación científica en Python. Proporciona arreglos multidimensionales de alto rendimiento y herramientas para trabajar con estos arreglos.

Para usar Numpy, primero necesitamos importar el paquete `numpy`. Lo podemos importar con el alias `np`:

In [ ]:
import numpy as np

###Arreglos

Un arreglo numérica es una cuadrícula de valores, todos del mismo tipo, y está indexado por una tupla de enteros no negativos. El número de dimensiones es el rango del arreglo; la forma (*shape*) de una matriz es una tupla de números enteros que dan el tamaño de la matriz a lo largo de cada dimensión.

Podemos inicializar matrices numpy de listas de Python anidadas y acceder a elementos usando corchetes:

In [ ]:
a = np.array([1, 2, 3])  # Crea un arreglo de rango 1
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Cambia un elemento del arreglo
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Crea un arreglo de rango 2
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)                   
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy también proporciona muchas funciones para crear matrices:

In [ ]:
a = np.zeros((2,2))  # Crea un arreglo con ceros en todas las posiciones
print(a, type(a))

[[0. 0.]
 [0. 0.]] <class 'numpy.ndarray'>


In [ ]:
b = np.ones((1,2))   # Crea un arreglo con unos en todas las posiciones
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7) # Crea un arreglo constante
print(c) 

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2)        # Crea una matriz identidad 2x2
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2)) # Crea un arreglo con valores aleatorios entre 0 y 1
print(e)

[[0.02789302 0.22678913]
 [0.25764036 0.06350848]]


###Array indexing

Numpy ofrece varias formas de indexar en arreglos.

Slicing: similar a las listas de Python, los arreglos numpy se les pueden hacer slices. Dado que los arreglos pueden ser multidimensionales, se debe especificar un slice para cada dimensión del arreglo:

In [ ]:
import numpy as np

# Crea el siguiente arreglo de rango 2 con forma (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Usamos slicing para recuperar un subarreglo que consiste de las 2 primeras
# filas y las columnas 1 y 2; b es el siguiente arreglo de forma (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)


[[2 3]
 [6 7]]


Un slice de un arreglo es una vista de los mismos datos, por lo que modificarla modificará la matriz original.

In [ ]:
print(a[0, 1]) 
b[0, 0] = 77    # b[0, 0] es la misma pieza de datos que a[0, 1]
print(a[0, 1]) 

2
77


También puede mezclar la indexación con enteros con la indexación con slices. Sin embargo, hacerlo producirá una matriz de rango más bajo que la matriz original.

In [ ]:
# Crea el siguiente arreglo de rango 2 con forma (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Dos formas de acceder a los datos de la fila central de la matriz.
Mezclar la indexación de enteros con *slices* produce una matriz de rango inferior, mientras que usar solo *slices* produce una matriz del mismo rango que la matriz original:

In [ ]:
row_r1 = a[1, :]    # Vista de rango 1 de la segunda fila de a
row_r2 = a[1:2, :]  # Vista de rango 2 de la segunda fila de a
row_r3 = a[[1], :]  # Vista de rango 2 de la segunda fila de a
print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# Podemos hacer la misma distinción al acceder a las columnas de un arreglo:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print ()
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Indexación entera de arreglos: cuando se indexa arreglos de números utilizando *slicing*, la vista de arreglo resultante siempre será una submatriz de la matriz original. Por el contrario, la indexación de matrices enteras le permite construir matrices arbitrarias utilizando los datos de otra matriz. Aquí hay un ejemplo:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Un ejemplo de indexación entera de arreglos.
# El arreglo resultante tendrá forma (3,) y es el siguiente: 
print (a[[0, 1, 2], [0, 1, 0]])

# El ejemplo anterior de indexación entera de arreglo es equivalente a esto:
print (np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [ ]:
# Al usar indexación entera de arreglos, se puede reutilizar el mismo elemento
# del arreglo original:
print (a[[0, 0], [1, 1]])

# Equivalente al ejemplo previo de indexación entera de arreglos
print (np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


Un truco útil con la indexación de matrices de enteros es seleccionar o mutar un elemento de cada fila de una matriz:

In [ ]:
# Creamos un arreglo nuevo del que seleccionaremos elementos
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print (a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Creamos un arreglo de índices
b = np.array([0, 2, 0, 1])

# Seleccionamos un elemento de cada fila usando los índices en b
print(a[np.arange(4), b])  # Imprime "[ 1  6  7 11]"

In [ ]:
# Mutamos un elemento de cada fila usando los índices en b
a[np.arange(4), b] += 10
print(a)

Indexación booleana de arreglos: la indexación booleana de arreglos permite seleccionar elementos arbitrarios de una matriz. Con frecuencia, este tipo de indexación se utiliza para seleccionar los elementos de una matriz que satisfacen alguna condición. Aquí hay un ejemplo:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Encuentra los elementos que son mayores que 2;
                    # esto devuelve un arreglo numpy de booleanos de la misma
                    # forma de a, donde cada componente de bool_idx informa
                    # si el elemento de a es > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# Usamos indexación booleana de arreglos para construir un arreglo de rango 1
# que consiste de los elementos que corresponden alos valores con True del
# arreglo bool_idx
print(a[bool_idx])

# Podemos hacer todo lo arrba con esta instrucción concisa:
print(a[a > 2])


[3 4 5 6]
[3 4 5 6]


Por brevedad, hemos omitido muchos detalles sobre la indexación de arreglos numpy; si quieres saber más debes leer la documentación.

###Tipos de datos

Cada arreglo numpy es una cuadrícula de elementos del mismo tipo. Numpy proporciona un gran conjunto de tipos de datos numéricos que puede utilizar para construir matrices. Numpy intenta adivinar un tipo de datos cuando crea una matriz, pero las funciones que construyen matrices generalmente también incluyen un argumento opcional para especificar explícitamente el tipo de datos. Aquí hay un ejemplo:

In [ ]:
x = np.array([1, 2])  # Permite a numpy elegir el tipo de datos
y = np.array([1.0, 2.0])  # Permite a numpy elegir el tipo de datos
z = np.array([1, 2], dtype=np.int64)  # Fuerza a un tipo particular de datos

print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


Puedes leer todo sobre tipos de datos numpy en la [documentación](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

###Matemática de arreglos

Las funciones matemáticas básicas operan componente a componente y están disponibles usando operadores y como funciones en el módulo numpy:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Suma componente a componente. Ambas producen el mismo arreglo.
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Resta componente a componente. Ambas producen el mismo arreglo.
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Multiplicación componente a componente. Ambas producen el mismo arreglo.
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# División componente a componente. Ambas producen el mismo arreglo.
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Raíz cuadrada componente a componente. Ambas producen el mismo arreglo.
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


A diferencia de de otros lenguajes, `*` es una multiplicación componente a componente, no una multiplicación de matrices. En su lugar, usamos la función `dot` para calcular los productos internos de los vectores, para multiplicar un vector por una matriz y para multiplicar matrices. `dot` está disponible como función en el módulo numpy y como método de instancia de objetos de matriz:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Producto interno de vectores. Ambos producen 219
print(v.dot(w))
print(np.dot(v, w))
print(v @ w)

219
219
219


In [ ]:
# Producto matricial / vector product; ambos producen el arreglo de rango 1 [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [ ]:
# Producto matricial / matrix product; ambos producen el arreglo de rango 2
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Para realizar otras operaciones de matrices típicas del álgebra lineal como el calculo de la matriz inversa, podemos utilizar el submódulo `linalg` de `numpy`:

In [ ]:
from numpy.linalg import inv

x = np.array([[1,2],[3,4]])
print(inv(x))

[[-2.   1. ]
 [ 1.5 -0.5]]


Numpy proporciona muchas funciones útiles para realizar cálculos en matrices; uno de los más útiles es `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Computa la suma de todos los elementos; imprime "10"
print(np.sum(x, axis=0))  # Computa la suma de cada columna; imprime "[4 6]"
print(np.sum(x, axis=1))  # Computa la suma de cada fila; imprime "[3 7]"

10
[4 6]
[3 7]


Puedes encontrar la lista completa de funciones matemáticas proporcionadas por numpy en la [documentación](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Además de calcular funciones matemáticas utilizando arreglos, con frecuencia necesitamos cambiar la forma o manipular datos en arreglos. El ejemplo más simple de este tipo de operación es la transposición de una matriz; para transponer una matriz, simplemente use el atributo T de un objeto de matriz:

In [ ]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v)
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


###Broadcasting

Broadcasting es un mecanismo poderoso que permite a numpy trabajar con matrices de diferentes formas al realizar operaciones aritméticas. Con frecuencia tenemos una matriz más pequeña y una matriz más grande, y queremos usar la matriz más pequeña varias veces para realizar alguna operación en la matriz más grande.

Por ejemplo, suponga que queremos agregar un vector constante a cada fila de una matriz. Podríamos hacerlo así:

In [ ]:
# Sumaremos el vectov a cada fila de la matriz x,
# guardando el resultado en la matriz y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Creamos una matriz vacía con la misma forma de x

# Suma el vector v a cada fila de la matriz x usando un bucle explícito
for i in range(4):
    y[i, :] = x[i, :] + v

print (y)

Esto funciona; sin embargo, cuando la matriz `x` es muy grande, calcular un buble explícito en Python podría ser lento. Tenga en cuenta que agregar el vector `v` a cada fila de la matriz `x` es equivalente a formar una matriz `vv` apilando múltiples copias de `v` verticalmente y luego realizar la suma de elementos de` x` y `vv`. Podríamos implementar este enfoque de esta manera:

In [ ]:
vv = np.tile(v, (4, 1))  # Apila 4 copias de v encima una de otra
print (vv)               # imprime "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Suma x & vv componente a componente
print (y)

El broadcasting de `numpy` nos permite realizar esta operación sin la necesidad de crear realmente multiples copias de `v`. Considere esta versión usando broadcasting:

In [ ]:
import numpy as np

# Sumaremos el vector v a cada fila de la matriz x,
# guardando el resultado en la matriz y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Sumamos v a cada fila de x usando broadcasting
print (y)

La línea `y = x + v` funciona aunque` x` tiene forma `(4, 3)` y `v` tiene forma` (3,) `debido al *broadcasting*; esta línea funciona como si `v` realmente tuviera la forma `(4, 3)`, donde cada fila sería una copia de `v`, y la suma se realizara por elementos.

El *broadcasting* de dos matrices juntas sigue estas reglas:

1. Si las matrices no tienen el mismo rango, antepon 1 a la forma de la matriz de rango inferior hasta que ambas formas tengan la misma longitud.
2. Se dice que las dos matrices son compatibles en una dimensión si tienen el mismo tamaño en la dimensión, o si una de las matrices tiene el tamaño 1 en esa dimensión.
3. Los arreglos pueden operarse usando *broadcasting* si son compatibles en todas las dimensiones.
4. Después del *broadcasting*, cada matriz se comporta como si tuviese una forma igual al máximo de formas de los dos elementos de entrada.
5. En cualquier dimensión donde una matriz tiene un tamaño 1 y la otra matriz tiene un tamaño mayor que 1, la primera matriz se comporta como si se hubiera copiado a lo largo de esa dimensión.

Si esta explicación no tiene sentido, intenta leer la explicación de la [documentación](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) o esta [explicación](http://wiki.scipy.org/EricsBroadcastingDoc).

Las funciones que admiten *broadcasting* se conocen como funciones universales. Puede encontrar la lista de todas las funciones universales en la [documentación](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Estas son algunas aplicaciones de la *broadcasting*:

In [ ]:
# Computar productos externos de vectores
v = np.array([1,2,3])  # v tiene forma (3,)
w = np.array([4,5])    # w tiene forma (2,)
# Para computar el producto externo, primero cambimos la forma de v para que sea
# un vector columna con forma; ahora podemos hacer broadcast contra w para 
# encontrar una salida de forma (3, 2), que es el producto externo de v & w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
# Sumar un vector a cada fila de una matriz
x = np.array([[1,2,3], [4,5,6]])
# x tiene forma (2, 3) & v tiene forma (3,) haciendo broadcast a (2, 3),
# resultando en la siguiente matriz:

print(x + v)

In [ ]:
# Sumar un vector a cada columna de una matriz
# x tiene forma (2, 3) & w tiene forma (2,).
# Si tranponemos x entonces tendrá forma (3, 2) y se puede hacer broadcast
# contra w para lleegar a un resultado de forma (3, 2); transponiedo el 
# resultado se llega al resultado final de forma (2, 3) que es la matriz x con
# el vector w sumado a cada columna. Obteniendo la siguiente matriz:

print((x.T + w).T)

In [ ]:
# Otra solución es cambiar la forma de w a un vector fila de forma (2, 1);
# luego podemos hacer broadcast contra x para producir el mismo resultado. 
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiplicar una matriz por una constante:
# x tiene forma (2, 3). Numpy trata los escalares como arreglos de forma ();
# estos pueden operarse con broadcast a la forma (2, 3), produciendo el
# siguiente arreglo:
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

Esta breve descripción general ha abordado muchas de las cosas importantes que necesita saber sobre numpy, pero está lejos de ser completa. Consulte la [referencia de numpy](http://docs.scipy.org/doc/numpy/reference/) para obtener más información sobre numpy.

##Matplotlib

Matplotlib es una biblioteca de graficado. En esta sección, haremos una breve introducción al módulo `matplotlib.pyplot`.

In [ ]:
import matplotlib.pyplot as plt

Al ejecutar este comando especial de iPython, mostraremos gráficos en línea:

In [ ]:
%matplotlib inline

###Plotting

La función más importante en `matplotlib` es plot, que le permite graficar datos 2D. Aquí hay un ejemplo simple:

In [ ]:
# Computa las cordenadas x & y para puntos en las curvas seno
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Hace un plot de los puntos usando matplotlib
plt.plot(x, y)

# Muestra la figura.
plt.show()

Con solo un poco de trabajo adicional, podemos hacer plot fácilmente de varias líneas a la vez, agregar un título, una leyenda y etiquetas de eje:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Hace un plot de los puntos usando matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

# Muestra la figura.
plt.show()

###Subplots 

Puedes hacer plots de diferentes cosas en la misma figura usando la función de `subplot`. Aquí hay un ejemplo:

In [ ]:
# Computa las cordenadas x & y para puntos en las curvas seno y coseno
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# DEfine una cuadrícula subplot que tiene alto 2 y ancho 1,
# y activa el primer subplot.
plt.subplot(2, 1, 1)

# Hace el primer plot
plt.plot(x, y_sin)
plt.title('Sine')

# Activa el segundo subplot y realiza el segundo plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Muestra la figura.
plt.show()

Puede leer mucho más sobre la función `subplot` en la [documentación](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).